### ISSUE TITLE
Erro php

### ISSUE THREAD

**Issue by maneirinha** [juniormarcati/os#10]
PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in /var/www/html/glpi/inc/toolbox.class.php at line 653
PHP Notice (8): Undefined index: color in /var/www/html/glpi/plugins/os/front/index.php at line 55
PHP Notice (8): Undefined index: textcolor in /var/www/html/glpi/plugins/os/front/index.php at line 56

está dando esse erro na tela inicial do plugin

**Comment by luizjr** [comment]
@maneirinha , @rjmvaz 

Tive o mesmo problema na versão 8.0 do PHP.

Eu fiz alguns testes, na versão **7.4 do PHP** ele para de mostrar esse erro!
Veja sé é possível trocar a versão no seu servidor/hospedagem
