### ISSUE TITLE
suporte a versão 10 glpi

### ISSUE THREAD

**Issue by apracz** [juniormarcati/os#14]
Esse plug-in requerGLPI >= 9.4e <9.6.

na versão 10 ele não tem suporte ainda, seria show se tive-se, desde ja agradeço

**Comment by rafacss** [comment]
alguma novidade para uso no GLPi 10.0.1? extrai a versão 0.1.2 na pasta plugins e ele não é exibido para instalação no GLPi 10.0.1.

**Comment by rafacss** [comment]
> alguma novidade para uso no GLPi 10.0.1? extrai a versão 0.1.2 na pasta plugins e ele não é exibido para instalação no GLPi 10.0.1.

mudei o nome da pasta para somente OS e apareceu e consegui instalar. Farei os testes, se encontrar algum problema eu reporto, obrigado!

**Comment by rafacss** [comment]
Não consegui usar no GLPi 10.0.1. Consegui instalar e ativar, porém quando entro no chamado, não é exibido aquela guia que gerar o arquivo da OS. no menu plugins, o nome aparece, mas ao entrar a tela fica branca e não aparece nada.

**Comment by LuizRGOliveira** [comment]
Aqui a 

> Esse plug-in requerGLPI >= 9.4e <9.6.
> 
> na versão 10 ele não tem suporte ainda, seria show se tive-se, desde ja agradeço

Para poder ver a pasta de dentro do módulo plugin é necessário alterá-la para os. Deixe somente como os. 
No entanto, o plugins não está rodando 100% como estava na versão 9.x.

**Comment by LuizRGOliveira** [comment]
> Não consegui usar no GLPi 10.0.1. Consegui instalar e ativar, porém quando entro no chamado, não é exibido aquela guia que gerar o arquivo da OS. no menu plugins, o nome aparece, mas ao entrar a tela fica branca e não aparece nada.

Realmente, a mesma situação ocorreu aqui. 
Vamos ver se o autor da um help.

**Comment by lukasabino** [comment]
O problema que constatei ao instalar o mesmo aqui na minha base: 10.0.1, ao instalar e habilitar o plugin, a tela do mesmo fica em branco ao acessar o submenu para realizar configurações.
Segue screenshot.

![image](https://user-images.githubusercontent.com/70410692/174445204-d8c69bf3-d930-4624-83d5-af04fb259512.png)

**Comment by AiresRuy** [comment]
Opa, eu abri um problema relacionado a isso, investigando eu encontrei os seguintes erros que relatei nesta aqui:
#18 

> O problema que constatei ao instalar o mesmo aqui na minha base: 10.0.1, ao instalar e habilitar o plugin, a tela do mesmo fica em branco ao acessar o submenu para realizar configurações. Segue screenshot.
> 
> ![image](https://user-images.githubusercontent.com/70410692/174445204-d8c69bf3-d930-4624-83d5-af04fb259512.png)

**Comment by juniormarcati** [comment]
Pessoal, conforme relatado no #18 a versão compatível com a versão 10.X.X é a versão 0.2.0 que ainda está em beta.
