### ISSUE TITLE
Adicionar campo na etiqueta

### ISSUE THREAD

**Issue by lmarcals** [juniormarcati/os#16]
Boa tarde,

Estou utilizando o plugin "fields" para adicionar novos campos na abertura de chamado.
Seria possível adicionar esses novos campos na etiqueta?

**Comment by juniormarcati** [comment]
@lmarcals por hora, não tenho planos em colocar informações vindas do plugin fields, não consigo imaginar como isso seria possível e também nenhum bom motivo. Quais informações você tem nele e que gostaria de informar na OS?
