### ISSUE TITLE
Não aparece ícone para instalação

### ISSUE THREAD

**Issue by ccaires** [juniormarcati/os#17]
Olá pessoal, tentei instalar o plugin mas não aparece a opção de instalação e somente essa mensagem: Função inexistente: plugin_OS_install plugin_OS_check_configFunção inexistente: plugin_OS_uninstall na área do GLPI. Alguém sabe informar qual pode ser o problema?

**Comment by AiresRuy** [comment]
Você tentou renomear o diretório para o nome OS apenas?
Outra coisa, as permissões dos arquivos e diretórios, proprietário e grupo estão ok?

> Olá pessoal, tentei instalar o plugin mas não aparece a opção de instalação e somente essa mensagem: Função inexistente: plugin_OS_install plugin_OS_check_configFunção inexistente: plugin_OS_uninstall na área do GLPI. Alguém sabe informar qual pode ser o problema?

**Comment by ccaires** [comment]
Sim, tive que colocar a versão antiga 0.1.2 do plugin e funcionou. A nova versão do plugin só apresenta a mensagem de erro na tela de Plugin no GLPI para instalar. Outra coisa, na parte de gerar a OS tanto para o cliente quanto para Entidade o nome da empresa está pegando no banco a parte do "comentário" não do "name" da tabela glpi_locations. Estou tentando ver se consigo resolver isso.

**Comment by AiresRuy** [comment]
Conseguiu resolver?

> Sim, tive que colocar a versão antiga 0.1.2 do plugin e funcionou. A nova versão do plugin só apresenta a mensagem de erro na tela de Plugin no GLPI para instalar. Outra coisa, na parte de gerar a OS tanto para o cliente quanto para Entidade o nome da empresa está pegando no banco a parte do "comentário" não do "name" da tabela glpi_locations. Estou tentando ver se consigo resolver isso.
