### ISSUE TITLE
Página em Branco v0.1.2 no GLPI 10.0.1

### ISSUE THREAD

**Issue by AiresRuy** [juniormarcati/os#18]
Prezado, 
Baixei a versão 0.1.2 do plugin, descompactei no diretório plugins do GLPI, renomeei para o nome "os" o diretório.
Instalei o plugin e habilitei o mesmo.
Após isso ao acessar a configuração do plugin eu recebo um erro de página em branco.

Encontrei os seguintes erros nos arquivos do plugin: 

- Problema 1:
no arquivo: front/index.php 
Logo no inicio, os includes tem um diretorio UP adicional, 

ORIGINAL:
include ('../../../inc/includes.php');
include ('../../../config/config.php');

Porém o correto são apenas 2 UP dir, ficando:
include ('../../inc/includes.php');
include ('../../config/config.php');

- Problema 2:
Estou recebendo um erro 404 (NOT FOUND) do servidor web no seguinte arquivo:
"GET /plugins/os/front/css/styles.termo.css HTTP/1.1" 404

O arquivo styles.termo.css está referenciado, mas não existe aqui no projeto.
Pesquisando, vi que ele é referenciado nos seguintes arquivos:
/plugins/os/front/os_cli.php
/plugins/os/front/os.php

Poderia verificar essa questão para nós @juniormarcati  ??

**Comment by lukasabino** [comment]
Aqui mesmo deixando somente 2 UP dir ainda permanece em branco, o que estranhei foi a linha do include da config, visto que não tem pasta config no repo do pluguin, mas sim só o arquivo config dentro da própria pasta _front_

![image](https://user-images.githubusercontent.com/70410692/174482645-0649abad-255e-4376-b955-4c4f37ccdb47.png)

![image](https://user-images.githubusercontent.com/70410692/174482651-12b1cc45-b773-4d19-be2d-cbed67adf03d.png)

![image](https://user-images.githubusercontent.com/70410692/174482654-5e5a173a-882d-426d-b1b1-0b6b8ce18d9c.png)

**Comment by AiresRuy** [comment]
Aqui também, eu tive alguns outros problemas mesmo assim.
Acho que na hora de dar o commit o @juniormarcati deixou alguns arquivos sem enviar para o repositório.

> Aqui mesmo deixando somente 2 UP dir ainda permanece em branco, o que estranhei foi a linha do include da config, visto que não tem pasta config no repo do pluguin, mas sim só o arquivo config dentro da própria pasta _front_
> 
> ![image](https://user-images.githubusercontent.com/70410692/174482645-0649abad-255e-4376-b955-4c4f37ccdb47.png)
> 
> ![image](https://user-images.githubusercontent.com/70410692/174482651-12b1cc45-b773-4d19-be2d-cbed67adf03d.png)
> 
> ![image](https://user-images.githubusercontent.com/70410692/174482654-5e5a173a-882d-426d-b1b1-0b6b8ce18d9c.png)

**Comment by juniormarcati** [comment]
Olá @AiresRuy  e @lukasabino eu ainda não verifiquei sobre o funcionamento da versão 0.1.X no GLPI 10, peço desculpas pela demora. O que eu venho trabalhando é na versão 0.2.X que ainda está em beta :(

De fato tive um problema na máquina que fazia os merges com o github e estou migrando tudo diretamente para o github do projeto de OS, aos poucos irá normalizar. Apesar de a primeira vista não acreditar que seja esse o problema, acho que o projeto 0.1 não deve rodar legal mesmo no GLPI10.

Em breve vou instalar o 0.1 em uma máquina com o 10 para verificar se estou errado. 
Por enquanto fica a sugestão de testarem o 0.2.0-beta3 que está no master do glpi-os no Github que acho que vocês podem ter o que precisam já nele.

**Comment by AiresRuy** [comment]
Opa @juniormarcati 
Então, eu fiz foi verificar no fonte do código as chamadas para os arquivos e vi que eles realmente não estão no source do repositorio do 0.1.2.

Nas telas de chamados tem a parte do Gerar OS, tanto cliente como retaguarda...
Mas acredito que seja alguma falha boba mesmo.
De toda forma vamos baixar o beta e fazer uns testes com ele.

No que eu puder ajuda-lo com testes, pode contar comigo!
> Olá @AiresRuy e @lukasabino eu ainda não verifiquei sobre o funcionamento da versão 0.1.X no GLPI 10, peço desculpas pela demora. O que eu venho trabalhando é na versão 0.2.X que ainda está em beta :(
> 
> De fato tive um problema na máquina que fazia os merges com o github e estou migrando tudo diretamente para o github do projeto de OS, aos poucos irá normalizar. Apesar de a primeira vista não acreditar que seja esse o problema, acho que o projeto 0.1 não deve rodar legal mesmo no GLPI10.
> 
> Em breve vou instalar o 0.1 em uma máquina com o 10 para verificar se estou errado. Por enquanto fica a sugestão de testarem o 0.2.0-beta3 que está no master do glpi-os no Github que acho que vocês podem ter o que precisam já nele.

**Comment by lukasabino** [comment]
@juniormarcati 

Opa! De fato a versão 0.2.X da branch do repo está pelo menos abrindo no GLPI 10.0.1, porém ao configurar dá um certo erro na escrita da logo, creio que pode ser permissão na máquina aqui, mas fica a ressalva.

Irei testar mais durante a semana, qualquer outro adendo retorno aqui! No que precisar também, sigo a disposição para ajudar.

![image](https://user-images.githubusercontent.com/70410692/174915443-2e6713d2-b1ed-48e5-a4a7-8655b49cf000.png)

**Comment by juniormarcati** [comment]
@lukasabino faltou permissão na pasta pics, dentro da pasta do plugin.

**Comment by bonanati** [comment]
Tentei abrir a versão 0.2 Beta no glpi 10.0.0.2 e não ativa.. alguém conseguiu rodar?

**Comment by juniormarcati** [comment]
@bonanati fiz o teste na versão 10.0.2 e por aqui não tive problemas para instalar e ativar ele.
Ele gerou algum erro na hora da tentativa de ativação do plugin?

**Comment by bonanati** [comment]
o meu na hora que vou habilitar da esse erro e não habilita.. :
not matched. It has been deactivated. in /www/wwwroot/chamados.dominio.com.br/src/Plugin.php on line 634

**Comment by juniormarcati** [comment]
@Israel-Kraisch poderia instalar a versão do beta6 e me retornar caso o problema continue?
