### ISSUE TITLE
CRSF

### ISSUE THREAD

**Issue by MsMatheus** [juniormarcati/os#20]
Tentei fazer a instalação no meu ambiente de homologação e deu erro na habilitação do plugin: Em não conformidade com CSRF! - 
Como posso resolver este problema?
estou usando a versão 9.5.6 do GLPI

**Comment by hldramos** [comment]
Altere o nome da pasta de instalação para "OS" com as letras minuscula.

**Comment by juniormarcati** [comment]
alterando o nome da pasta para "os" o problema é solucionado, também mudei o nome do projeto no GH para que isso não ocorra novamente. Obrigado.
