### ISSUE TITLE
REQUISIÇÃO DO PDF NO FORMCREATOR

### ISSUE THREAD

**Issue by N4m3r** [juniormarcati/os#22]
Gostaria de um ajudar, quando eu tento puxar a ordem de serviço pela forma simplificada extendida do formcreator o link de requisição mudar e não gera a os do ticket em aberto. 

como administrador ele tentar acessar esse link: 
https://jj-ferreira.com/glpi/front/ticket.form.php?id=2022072602

e quando tento gerar pelo formcreator ele tentar acessar 
https://jj-ferreira.com/glpi/plugins/formcreator/front/issue.form.php?id=72&tickets_id=2022040501

como posso mudar o endereçamento de requisição pra que ele gere corretamente!

**Comment by caiofelipe99** [comment]
Também estou com o mesmo problema 
Notei que no iframe da OS no FormCreator ele leva para o seguinte diretório: http://localhost/glpi/plugins/formcreator/plugins/os/front/os_pdf.php?id=1479

Tentei copiar o plugin para a pasta que o formcreator estava apontando, mas sem sucesso. Aparecendo o erro a seguir
![image](https://user-images.githubusercontent.com/81644840/192821374-226bca0a-564b-4f03-b639-4257df5a0622.png)

**Comment by juniormarcati** [comment]
Está corrigido e em breve sera divulgado novo beta.
