### ISSUE TITLE
REDIRECIONAMENTO QR CODE

### ISSUE THREAD

**Issue by motinha22** [juniormarcati/os#23]
Boa tarde,

É possível mudar o link de redirecionamento do QR CODE?
Quando faço a leitura o mesmo é encaminhado para http://192.168.100.86

**Comment by itaymbere** [comment]
@motinha22 corrija na configuração do seu VirtualHost setando a diretiva servername corretamente!

**Comment by motinha22** [comment]
Boa noite,
Fiz exatamente isso, criei um vhost e já com servername configurado, mas o qr code não muda o link gerado.

**Comment by itaymbere** [comment]
@juniormarcati da uma olhada por gentileza no pedido do @motinha22!! SAPS

**Comment by juniormarcati** [comment]
@motinha22 
desculpe a demora, retomando agora o projeto, conseguiu resolver? tenho uma versão lançada como beta5 que não é para ocorrer o problema. Essa semana estarei lançando uma nova versão com alguns ajustes.
