### ISSUE TITLE
Restringir visualização do menu Ordem de Serviço

### ISSUE THREAD

**Issue by danvasc** [juniormarcati/os#24]
Prezados,

É possível limitar a visualização do submenu Plugins > Ordem de Serviço apenas para alguns perfis?

Não quero que os técnicos tenham acesso e possam fazer alterações nas informações que constam na OS.

**Comment by itaymbere** [comment]
@juniormarcati isso é feito pelo perfil do usuário ne?

**Comment by danvasc** [comment]
Eu criei um perfil teste e removo todas as permissões, mas mesmo assim o submenu OS permaneceu visível. 

Para os técnicos não mexerem nas configurações eu comentei os botões da página.

**Comment by Israel-Kraisch** [comment]
> Eu criei um perfil teste e removi todas as permissões, mas mesmo assim o submenu OS permaneceu visível.
> 
> Para os técnicos não mexerem nas configurações eu comentei os botões da página.

Também tive de esconder os botões, assim somente o perfil Super-Admin consegue configurar o plugin.

**Comment by juniormarcati** [comment]
@danvasc 
No beta6 da versão 0.2.0 foi resolvida a questão da permissão. 
Não é uma solução definitiva pois o perfil dos usuários de técnicos precisa estar sem permissão para as configurações, por hora, isso deve ajudar, no futuro penso em lançar um menu específico para o plugin nas configurações.
