### ISSUE TITLE
Possível solução : tela branca no glpi 10.0.x

### ISSUE THREAD

**Issue by aspiranteabodybuilder** [juniormarcati/os#25]
Testei o plugin em 2 instalações : 10.0.7 e 0.9
Após instalar, ao acessar plugins > ordem de serviço retorna uma página branco
Consegui resolver fazendo o seguinte procedimento : acessa o banco, apaga todas as tabelas que o plugin os criou, acessa a pasta /plugins e apaga o plugin. Volta no glpi, limpa o plugin, instala novamente, ativa e acessa.

Para mim só resolveu assim

**Comment by aspiranteabodybuilder** [comment]
Testado na versão : 0.2.0-beta3

**Comment by juniormarcati** [comment]
@aspiranteabodybuilder 
conseguiu resolver seu caso? desculpe, estava afastado.
