### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Shirakiim** [juniormarcati/os#26]
"I am facing a problem. I have installed the plugin on GLPI 10.0.3, and it is giving a series of errors and not generating the work orders on the sheet."

Notice: Undefined index: color in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 39

Notice: Undefined index: textcolor in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 40

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 105

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 128

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 144

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 149

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 150

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 155

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 156

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 161

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 162

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 167

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\glpi\plugins\os\front\configOs.php on line 168

**Comment by juniormarcati** [comment]
I'm working on it

**Comment by juniormarcati** [comment]
The problem has been resolved in the 0.2.0-beta6. 
Please check.
