### ISSUE TITLE
Traducir a español

### ISSUE THREAD

**Issue by lexcorp** [juniormarcati/os#5]
Hola Junior, me gustaría poder ayudar a traducir el plugin al idioma español, en la carpeta locales del plugin coloque los archivos es_ES.mo y es_ES.po con la traducción pero no funciona, ya que no cambia el idioma del texto. Adicionalmente te comento que para modificar los textos en el PDF fue necesario modificar directamente el código, existe alguna forma de cambiar el lenguaje en el PDF sin tener que modificar directamente el código?

**Comment by juniormarcati** [comment]
@lexcorp estou estudando a possibilidade, a melhor forma é adequar aos arquivos .po e .mo.
Já estou estudando.
